name: Integration Deckstats

on:
  schedule:
    - cron: '6 7 * * 1' # https://crontab.guru/#6_7_*_*_1
  workflow_dispatch:

jobs:
  integration_deckstats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          python-version: 3.14.2
          poetry-version: 2.2.1
      - name: Run tests
        run: make test-integration WEBSITE=deckstats
